default: &default
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  twitter:
    consumer_key: <%= ENV['TWITTER_CONSUMER_KEY'] %>
    consumer_secret: <%= ENV['TWITTER_CONSUMER_SECRET'] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
